### ISSUE TITLE
Unpin django-treebeard strict version

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-cms/djangocms-googlemap#102]
Working on [[BUG] Adding model to existing plugin, existing plugin instances disappear](https://github.com/django-cms/django-cms/issues/7476) I have next issue related to django-treebeard: `treebeard.exceptions.NodeAlreadySaved: Attempted to add a tree node that is already in the database`

Right now we have at [setup.py](https://github.com/django-cms/djangocms-googlemap/blob/42a5b81dcfd69a3559434e23772c6c8fcda0cae9/setup.py#L10) next strict version checking: `django-treebeard>=4.3,<4.5`

The way I propose is `django-treebeard>=4.0,!=4.5.1`.

@fsbraun , do you think it can work for us? If yes, I can provide PR for it.

**Comment by DmytroLitvinov** [comment]
I see that at djangocms-snippet it was fixed, but not released - https://github.com/django-cms/djangocms-snippet/commit/a4f369837cb54ae4e349887face4b65219bec27f

**Comment by fsbraun** [comment]
I just commented on your PR! Thank you! Let's get this done and released!

**Comment by fsbraun** [comment]
@DmytroLitvinov I just released djangocms-snippet 3.1.1 unpining django-treebeard.
